language: rust
os: linux
dist: bionic
before_script:
  - rustup component add clippy
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install llvm-10 llvm-10-dev
  - sudo apt-get install lld-10

script:
  - LLVM_SYS_100_PREFIX=/usr/lib/llvm-10 cargo build
  - cargo clippy -- -D warnings
  - mkdir output
  - cargo test --verbose
  - python3 run_move_tests.py compilation
cache: cargo