language: rust
os: linux
dist: bionic
before_script:
  - rustup component add clippy
  - sudo apt-get update
  - sudo apt-get install python3 clang-10 llvm-10

script:
  - cargo clippy -- -D warnings
  - mkdir output
  - cargo run libra tests/move_tests/counter.flint
  - cargo run libra tests/move_tests/rectangle.flint
  - cargo run libra tests/move_tests/shapes.flint
  - cargo run libra tests/move_tests/traffic_lights.flint
  - cargo run libra tests/move_tests/assert.flint
  - cargo run libra tests/move_tests/callerprotections_counter.flint
  - cargo run libra tests/move_tests/factorial.flint
  - cargo run libra tests/move_tests/inits.flint
  - cargo run libra tests/move_tests/operators.flint
  - cargo run libra tests/move_tests/public_and_visible.flint
  - cargo run libra tests/move_tests/typestates_counter.flint
  - python3 run_move_tests.py compilation
  - cargo test --verbose
cache: cargo
