language: rust
os: linux
dist: xenial
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D clippy::unnecessary_operation -D clippy::complexity -D clippy::correctness -A clippy::unnecessary-unwrap --verbose
  - mkdir output
  - cargo run libra tests/counter.flint
  - cargo run libra tests/shapes.flint
  - cargo run libra tests/traffic_lights.flint
  - cargo test --verbose
cache: cargo    
